CXXFLAGS := -std=c++11  -Isrc/ -Iobj/ -g

all: int

clean:
	rm -rf obj/ int

int:
	mkdir -p obj/
	bison -y --report=state --graph --warning=all -d -o obj/lua.tab.cpp src/lua.yy
	flex -o obj/lua.yy.cpp src/lua.ll
	g++ -c obj/lua.tab.cpp -o obj/lua.tab.o $(CXXFLAGS)
	g++ -c obj/lua.yy.cpp -o obj/lua.yy.o $(CXXFLAGS)
	g++ -c src/main.cpp -o obj/main.o $(CXXFLAGS)
	g++ -c src/evaluate.cpp -o obj/evaluate.o $(CXXFLAGS)
	g++ obj/lua.tab.o obj/lua.yy.o obj/main.o obj/evaluate.o -o int